version: '3'

services:
  relay:
    image: sergeyitsib/phone-search:latest
    container_name: phone-search
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: '3200'
      CORS_ORIGIN: '*'
    ports:
      - '3200:3200'
    networks:
      - phone-search-net

networks:
  phone-search-net:
    driver: bridge
